#Set a variable for the metadata validity time
{{$mtime := "2016-04-06T00:00:00 PDT"}}

#This configures what the base URI for everything else
#is, and is what the permissions will be looked for on
svc_base_uri: 410.dev/plugctl/front
meta:
  room:
    val: 410
    ts: {{$mtime}}
  floor:
    val: 4
    ts: {{$mtime}}
plugs:
  - #0
    meta:
      common-names:
        val: heater, heat
        ts: {{$mtime}}
      device:
        val: fan
        ts: {{$mtime}}
  - #1
    meta:
      common-names:
        val: fan, fans
        ts: {{$mtime}}
      device:
        val: heater
        ts: {{$mtime}}
  - #2
    meta:
      common-names:
        val: light, lights, lamp
        ts: {{$mtime}}
      device:
        val: light
        ts: {{$mtime}}
  - #3
    base: 3
  - #4
    base: 4
  - #5
    base: 5
  - #6
    base: 6
  - #7
    base: 7
